kind: pipeline
type: docker
name: alsap_frontend

volumes:
  - name: frond_end_dist
    host:
      path: /www/wwwroot/alsap.tracesec.cn

steps:
  - name: npm-package
    image: node:latest
    volumes:
      - name: frond_end_dist
        path: /usr/local/frond_end 
    commands:
      - npm config set registry https://registry.npm.taobao.org/ # 将npm注册表设置为淘宝镜像
      - npm install
      - npm run build
      - cp -r /drone/src/dist /usr/local/frond_end/


# 可限制哪些分支可以推送自动CICD
trigger:
  branch:
    - main
