kind: pipeline
type: docker
name: alsap_frontend

volumes:
  - name: frond_end_dist
    host:
      path: /www/wwwroot/alsap.tracesec.cn

steps:
  - name: npm-package
    image: node:20-slim
    volumes:
      - name: frond_end_dist
        path: /usr/local/frond_end
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - pwd
      - du -sh *
      - npm config set registry https://registry.npmmirror.com
      - npm install -g pnpm || npm install -g pnpm || npm install -g pnpm  # Retry logic
      - pnpm config set store-dir /drone/src/node_modules/.pnpm-store
      - pnpm install || pnpm install || pnpm install  # Retry logic
      - npm run build
      - cp -r ./dist /usr/local/frond_end/


trigger:
  branch:
    - main
