kind: pipeline
type: docker
name: alsap_frontend

volumes:
  - name: frond_end_dist
    host:
      path: /www/wwwroot/alsap.tracesec.cn
  - name: node_modules
    host:
      path: /home/drone/cache/node_modules
steps:
  - name: npm-package
    image: node:18.20.4-alpine
    volumes:
      - name: frond_end_dist
        path: /usr/local/frond_end
      - name: node_modules
        path: /drone/src/node_modules
    commands:
      - pwd
      - du -sh *
      - npm config get registry
      - npm config set registry https://registry.npmmirror.com/
      - npm config get registry
      - npm install --legacy-peer-deps || npm install
      - npm run build || max build
      - cp -r ./dist /usr/local/frond_end/


trigger:
  branch:
    - main
